In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_moons, make_circles, make_classification
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

data = pd.read_csv('final.csv')
#map(complex, dat['theta_fft'])

data = data.drop(['theta_fft', 'alpha_low_fft', 'alpha_high_fft', 'beta_fft', 'gamma_fft'], axis=1)

print(data)

        theta_mean  theta_median     theta_std     theta_var  alpha_low_mean  \
0     4.599176e-14  4.040364e-14  1.347478e-14  1.815698e-28    3.590780e-14   
1     3.080074e-13  3.816345e-13  1.536259e-13  2.360092e-26    1.187150e-13   
2     1.233333e-13  1.457773e-14  1.878236e-13  3.527769e-26    3.140773e-14   
3     1.642191e-14  1.466337e-14  6.792232e-15  4.613441e-29    2.033881e-14   
4     1.391187e-13  8.051837e-14  1.264497e-13  1.598953e-26    6.290670e-14   
5     1.580080e-14  1.028145e-14  1.098144e-14  1.205919e-28    1.544054e-14   
6     1.391775e-14  1.519046e-14  5.780667e-15  3.341611e-29    1.169633e-14   
7     1.465756e-14  1.399476e-14  1.027029e-14  1.054790e-28    1.819892e-14   
8     1.305207e-14  1.282866e-14  3.314828e-15  1.098808e-29    7.440759e-15   
9     3.129974e-14  2.269397e-14  2.703144e-14  7.306989e-28    3.368482e-14   
10    7.572631e-13  5.971140e-13  6.413753e-13  4.113623e-25    2.650724e-13   
11    4.867639e-14  3.453597e-14  4.0642

In [19]:
X_data = data.drop('state', axis=1)
X_data.shape
y_data = data['state']
y_data.shape

(5043,)

In [20]:
scaler = StandardScaler()
X_data = scaler.fit_transform(X_data)

In [21]:
model = RandomForestClassifier(class_weight='balanced', max_depth=30, max_features=1, min_samples_leaf=1, min_samples_split=10, n_estimators=1000, random_state=1, warm_start=False)
model.fit(X_data, y_data)                  # 3. fit model to data

RandomForestClassifier(bootstrap=True, class_weight='balanced',
            criterion='gini', max_depth=30, max_features=1,
            max_leaf_nodes=None, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=1,
            min_samples_split=10, min_weight_fraction_leaf=0.0,
            n_estimators=1000, n_jobs=None, oob_score=False,
            random_state=1, verbose=0, warm_start=False)

In [22]:
import pickle
# save the classifier
with open('eeg_classifier.pkl', 'wb') as fid:
    pickle.dump(model, fid)

Wall time: 9.24 s
Wall time: 4.36 s
Wall time: 4.44 s
Wall time: 4.7 s
Wall time: 4.22 s
Wall time: 4.59 s
Wall time: 4.34 s
Wall time: 4.5 s
Wall time: 4.39 s
Wall time: 4.39 s
Mean:  0.53778071334214
Std:  0.02118924946268074
{'C': 11, 'gamma': 1}
0.5323645970937912


Confusion Matrix: 
[[ 41  24  28]
 [ 48 355 164]
 [161 137 303]]

 Classification Report: 
              precision    recall  f1-score   support

       bored       0.16      0.44      0.24        93
        calm       0.69      0.63      0.66       567
  frustrated       0.61      0.50      0.55       601

   micro avg       0.55      0.55      0.55      1261
   macro avg       0.49      0.52      0.48      1261
weighted avg       0.61      0.55      0.58      1261


Accuracy:  0.5543219666931007


AttributeError: 'SVC' object has no attribute 'feature_importances_'